#!/bin/bash
# Fix
sudo /opt/homebrew/bin/yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo /opt/homebrew/bin/yabai --load-sa"

# Main
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config split_ratio                  0.55
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
# yabai -m config external_bar                 all:0:26
yabai -m config window_border_width          1
yabai -m config window_border                on
yabai -m config active_window_border_color   0xffe78a4e
yabai -m config normal_window_border_color   0xff1d2021

# yabai -m config active_window_border_color   0xFFA0ABF5
# yabai -m config normal_window_border_color   0xB26D738C

yabai -m config layout                       bsp
yabai -m config top_padding                  30 
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

yabai -m rule --add title=choose manage=off
yabai -m rule --add title=Microsoft\ Teams\ Notification border=off
yabai -m signal --add event=space_changed action="node ~/.config/yabai/hammerspoon_bsp_helper.js"

# Adds
yabai -m config focus_follows_mouse autoraise

# floating windows are always on top (default: off)
yabai -m config window_topmost on

# Create Sapce on focused windows
yabai -m space --create
yabai -m config auto_balance                off

# Sketchybar BS

yabai -m signal --add event=window_created action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=window_focused action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=space_changed action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
